name: Optimized ImmortalWrt Build

concurrency: 
  group: build-${{ github.ref }}
  cancel-in-progress: true

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    env:
      IMAGEBUILDER_URL: "https://downloads.immortalwrt.org/releases/24.10.1/targets/x86/64/immortalwrt-imagebuilder-24.10.1-x86-64.Linux-x86_64.tar.zst"
      IMAGEBUILDER_ARCHIVE: "immortalwrt-imagebuilder-24.10.1-x86-64.Linux-x86_64.tar.zst"
      IMAGEBUILDER_DIR: "immortalwrt-imagebuilder-24.10.1-x86-64.Linux-x86_64"
      SOFTS_DIR: "softs"
      PLUGINS_FILE: "plugins.list"
      OUTPUT_DIR: "output"
      IMAGE_SIZE: "4096MB"
      ROOTFS_SIZE: "4096"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        sudo apt update -y
        sudo xargs -a dependencies.txt apt install -y
        sudo timedatectl set-ntp on
        sudo apt install -y zstd pv rsync coreutils libc6-i386 lib32stdc++6
        
    - name: Create URL hash for caching
      id: url-hash
      run: |
        HASH=$(echo -n "$IMAGEBUILDER_URL" | sha256sum | awk '{print $1}')
        echo "url_hash=$HASH" >> $GITHUB_OUTPUT

    - name: Create cache directories
      run: |
        mkdir -p ${{ env.IMAGEBUILDER_DIR }}
        touch ${{ env.IMAGEBUILDER_ARCHIVE }}
        sudo chown -R $USER:$USER ${{ env.IMAGEBUILDER_DIR }}

    - name: Cache ImageBuilder
      uses: actions/cache@v4
      id: cache-imagebuilder
      with:
        path: |
          ${{ env.IMAGEBUILDER_ARCHIVE }}
          ${{ env.IMAGEBUILDER_DIR }}
        key: ${{ runner.os }}-imagebuilder-${{ steps.url-hash.outputs.url_hash }}
        restore-keys: |
          ${{ runner.os }}-imagebuilder-

    - name: Download and extract ImmortalWrt ImageBuilder
      if: steps.cache-imagebuilder.outputs.cache-hit != 'true'
      run: |
        FREE_SPACE=$(df -h . | awk 'NR==2 {print $4}')
        echo "可用磁盘空间: $FREE_SPACE"
        wget -q --show-progress --continue --tries=3 --waitretry=10 $IMAGEBUILDER_URL
        zstd -d -c $IMAGEBUILDER_ARCHIVE | tar -xvf - --no-overwrite-dir
        find $IMAGEBUILDER_DIR -type f | head -5 | xargs -I{} ls -lh {}

    # ========= 关键修复区域 =========
    - name: Fix directory permissions
      run: |
        sudo chown -R $USER:$USER ${{ env.IMAGEBUILDER_DIR }}
        find ${{ env.IMAGEBUILDER_DIR }} -type d -exec chmod 755 {} \;
        # 修复1：仅当目录存在时才修改权限[1](@ref)
        if [ -d "${{ env.IMAGEBUILDER_DIR }}/staging_dir/host/bin" ]; then
          find ${{ env.IMAGEBUILDER_DIR }}/staging_dir/host/bin -type f -exec chmod +x {} \;
        fi

    - name: Prepare custom IPK packages
      run: |
        mkdir -p $IMAGEBUILDER_DIR/packages/custom/base
        if [ -d "$SOFTS_DIR" ]; then
          find "$SOFTS_DIR" -type f -name "*.ipk" -exec cp -v {} "$IMAGEBUILDER_DIR/packages/custom/base/" \;
        fi
        sudo chown -R $USER:$USER $IMAGEBUILDER_DIR/packages/custom

    - name: Precompile host tools
      run: |  # 修复2：确保工具目录生成[4](@ref)[6](@ref)
        cd ${{ env.IMAGEBUILDER_DIR }}
        make -j $(nproc) tools/install
        make -j $(nproc) toolchain/install
        # 修复后权限设置
        find staging_dir/host/bin -type f -exec chmod +x {} \;
    # ===============================

    - name: Initialize package index
      run: |
        cd ${{ env.IMAGEBUILDER_DIR }}
        mkdir -p keys
        touch keys/secret.key
        
        export FORCE_UNSAFE_CONFIGURE=1
        export PKG_HASH=skip
        
        make package_index V=s 2>&1 | tee build.log
        
        if ! grep -q "package index generated" build.log; then
          echo "❌ 包索引生成失败 - 详细错误:"
          grep -i "error\|fail" build.log || true
          exit 1
        fi
        echo "✅ 包索引成功生成"

    - name: Cache package index
      uses: actions/cache@v4
      with:
        path: ${{ env.IMAGEBUILDER_DIR }}/bin/packages
        key: ${{ runner.os }}-packages-${{ hashFiles('plugins.list') }}

    - name: Parse plugins and packages
      id: get_pkgs
      run: |
        BASE_PKGS=""
        if [ -f "$PLUGINS_FILE" ]; then
          BASE_PKGS=$(grep -vE '^\s*#|^\s*$' "$PLUGINS_FILE" | parallel -j $(nproc) echo {} | tr '\n' ' ')
        fi

        CUSTOM_PKGS=""
        if [ -d "$IMAGEBUILDER_DIR/packages/custom/base" ]; then
          for ipk in "$IMAGEBUILDER_DIR/packages/custom/base/"*.ipk; do
            [ -e "$ipk" ] || continue
            pkgname=$(basename "$ipk" | awk -F_ '{print $1}')
            CUSTOM_PKGS="$CUSTOM_PKGS $pkgname"
          done
        fi

        ALL_PKGS=$(echo "$BASE_PKGS $CUSTOM_PKGS" | tr ' ' '\n' | sort -u | xargs)
        echo "FINAL_PKGS=$ALL_PKGS" >> $GITHUB_ENV

    - name: Build firmware with increased space
      run: |
        set -euxo pipefail
        cd $IMAGEBUILDER_DIR
        
        while true; do
          df -h .
          sleep 30
        done &
        DISK_MONITOR_PID=$!
        
        echo "CONFIG_TARGET_ROOTFS_PARTSIZE=$ROOTFS_SIZE" >> .config
        
        export FORCE_UNSAFE_CONFIGURE=1
        export PKG_HASH=skip
        
        make -j $(($(nproc))) V=sc image \
          PACKAGES="$FINAL_PKGS" \
          FILES=../files \
          IMAGE_SIZE="$IMAGE_SIZE"
        
        kill $DISK_MONITOR_PID
        
        mkdir -p ../$OUTPUT_DIR
        cp -Pv bin/targets/x86/64/* ../$OUTPUT_DIR/

    - name: Clean build intermediates
      run: |
        cd $IMAGEBUILDER_DIR
        make clean
        sudo rm -rf build_dir/ staging_dir/ tmp/
        df -h .

    - name: Verify firmware files
      run: |
        echo "==== Firmware files ===="
        ls -lh ${{ env.OUTPUT_DIR }}
        for file in ${{ env.OUTPUT_DIR }}/*; do
          if [[ $file == *.tar.gz ]]; then
            tar -tzf "$file" >/dev/null || echo "⚠️ Corrupted file: $file"
          fi
        done

    - name: Upload firmware to Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: immortalwrt-x86-64
        path: ${{ env.OUTPUT_DIR }}

    - name: Generate release tag
      id: release_tag
      run: |
        echo "tag=auto-build-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.release_tag.outputs.tag }}
        name: "ImmortalWrt x86_64 Firmware ${{ steps.release_tag.outputs.tag }}"
        body: |
          Automated build includes:
          - Base packages: `${{ env.FINAL_PKGS }}`
          - Custom IPKs from softs directory
        files: ${{ env.OUTPUT_DIR }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Normalize permissions for caching
      if: always()
      run: |
        sudo chown -R $USER:$USER ${{ env.IMAGEBUILDER_DIR }}
        find ${{ env.IMAGEBUILDER_DIR }} -type f -exec chmod 644 {} \;
