name: Build ImmortalWRT Firmware

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # 根据编译需求调整超时时间

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取所有历史记录

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y zstd build-essential libncurses-dev

    - name: Download and extract ImageBuilder
      run: |
        curl -LO https://downloads.immortalwrt.org/releases/24.10.1/targets/x86/64/immortalwrt-imagebuilder-24.10.1-x86-64.Linux-x86_64.tar.zst
        tar -I zstd -xf immortalwrt-imagebuilder-*.tar.zst
        rm immortalwrt-imagebuilder-*.tar.zst
        mv immortalwrt-imagebuilder-* imagebuilder

    - name: Apply custom configuration
      run: |
        cp .config imagebuilder/
        cp feeds.conf.default imagebuilder/
        cd imagebuilder
        make defconfig  # 应用配置文件

    - name: Build firmware
      run: |
        cd imagebuilder
        make -j$(nproc)  # 使用所有可用核心编译

    - name: Upload artifacts to workflow
      uses: actions/upload-artifact@v4
      with:
        name: firmware-binaries
        path: imagebuilder/bin/targets/*/*/
        retention-days: 7

    - name: Create release and upload assets
      if: success() && github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v2
      with:
        name: "Firmware Build ${{ github.run_number }}"
        tag_name: "firmware-${{ github.run_id }}"
        body: "Automatically built ImmortalWRT firmware"
        draft: false
        prerelease: false
        files: |
          imagebuilder/bin/targets/*/*/*.bin
          imagebuilder/bin/targets/*/*/*.gz
